<a href="https://colab.research.google.com/github/iankim20/-/blob/AI-and-medicine/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive                #구글드라이브에 마운트
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [ ]:
!ls '/gdrive/Team Drives/SevAIClass/LITS17'       #팀드라이브에 접속

segmentation-0.nii    segmentation-41.nii  volume-100.nii  volume-42.nii
segmentation-100.nii  segmentation-42.nii  volume-101.nii  volume-43.nii
segmentation-101.nii  segmentation-43.nii  volume-102.nii  volume-44.nii
segmentation-102.nii  segmentation-44.nii  volume-103.nii  volume-45.nii
segmentation-103.nii  segmentation-45.nii  volume-104.nii  volume-46.nii
segmentation-104.nii  segmentation-46.nii  volume-105.nii  volume-47.nii
segmentation-105.nii  segmentation-47.nii  volume-106.nii  volume-48.nii
segmentation-106.nii  segmentation-48.nii  volume-107.nii  volume-49.nii
segmentation-107.nii  segmentation-49.nii  volume-108.nii  volume-4.nii
segmentation-108.nii  segmentation-4.nii   volume-109.nii  volume-50.nii
segmentation-109.nii  segmentation-50.nii  volume-10.nii   volume-51.nii
segmentation-10.nii   segmentation-51.nii  volume-110.nii  volume-52.nii
segmentation-110.nii  segmentation-52.nii  volume-111.nii  volume-53.nii
segmentation-111.nii  segmentation-53.nii  volume-11

In [ ]:
!pip install nibabel
import os
import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt

LITS_DIR = '/gdrive/Team Drives/SevAIClass/LITS17'



NameError: ignored

In [ ]:

img=nib.load(os.path.join(LITS_DIR, 'segmentation-73.nii'))

data=img.get_fdata()
print(data.shape)
print(type(data))
print(data[:, :, 100])


(512, 512, 121)
<class 'numpy.memmap'>
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:

print(img.header.get_zooms())
header=img.header.get_zooms()
size=header[0]*header[1]*header[2]

slice100=data[:, :, 100]
get_indices=np.nonzero(slice100)

maskslice=np.ma.masked_values(slice100,1.0)

print(slice100.sum()*size)

print(maskslice.sum())



(0.9511719, 0.9511719, 4.0)
79065.98376464844
244.0


In [ ]:
volume = np.zeros(131)


def vol(imgfile):
  volume=0
  voxel_size = imgfile.header.get_zooms()
  voxel_volume = voxel_size[0]*voxel_size[1]*voxel_size[2]
  
  data=imgfile.get_fdata()
  N=data.shape[2]
  for i in range(N):
    volume += voxel_volume*np.count_nonzero(data[:, :, i])
    
  return volume
    
    
for i in range(131):
  img = nib.load(os.path.join(LITS_DIR, 'segmentation-%d.nii' % i))
  volume[i] = vol(img)
  print(volume[i])


1366051.8493652344
1486431.6312382221
1924447.2306175232
1560860.7577323914
3144348.213724375
1435887.3637908697
1886647.9144248962
1715650.9165420532
1899724.569595337
1548419.6640014648
1706466.1237182617
1473419.6179199219
1800541.609096527
1365586.7481689453
1430854.3385925293
1385848.4350204468
1399497.6708984375
1603829.505008757
1320757.371790707
1755115.4136943817
1885358.449280262
1782411.7133674622
1344574.4788486958
1252435.1773428917
1374862.01877594
1247668.3669742942
1219966.7852342725
1286075.0552538037
2865131.0
1648024.0
2375079.0
1132432.0
2124505.0
1828493.0
1461944.0
3215090.0
1265420.0
1872022.0
1692716.0
3341433.0
2063109.0
1633641.0
1389572.0
2717185.0
2106497.0
1220564.0
583208.0
1359697.0
888794.0
728813.0
710996.0
781190.0
759594.0
1615946.4486572742
1803650.9448242188
1887107.5362360477
2237815.8393228054
1859502.2277832031
1249416.38858819
1403944.3328401446
2400561.8259937763
1625939.1022372246
1185119.1525399685
1743557.2428209782
2193236.60081172
870206.0

In [ ]:
f = open('HW1_BCB.csv','w',encoding='utf-8')
wr = csv.writer(f)
wr.writerow(['FileNum','LiverSize'])
for i, vol in enumerate(volume):
  wr.writerow([i,vol])
f.close()